server:
  port: 8088
spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.91.128
    port: 6379
    database: 0